'use client';
import Link from 'next/link';
import { useParams } from 'next/navigation';
import { Check, Download, Edit3, FileText, History, RefreshCw, Save, ShieldCheck } from 'lucide-react';
import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { DeclarationCoverageMatrix } from '@/components/shared/declaration-coverage-matrix';
import { ErrorState } from '@/components/shared/error-state';
import { EvidenceViewer } from '@/components/shared/evidence-viewer';
import { LoadingState } from '@/components/shared/loading-state';
import { StatusBadge } from '@/components/shared/status-badge';
import { WhyThisVerdict } from '@/components/shared/why-this-verdict';
import { getInspection, inspectionImageUrl, reportUrl, submitCorrection, submitReview } from '@/lib/api-client';
import { confidence, fieldLabel, formatBytes, formatDate, REVIEW_LABELS, STATUS_LABELS } from '@/lib/format';
import type { Inspection, ReviewStatus } from '@/lib/types';

export default function InspectionDetailPage() {
  const id = Number(useParams<{ id: string }>().id); const [inspection, setInspection] = useState<Inspection>(); const [error, setError] = useState(''); const [selected, setSelected] = useState('');
  const load = useCallback(() => { if (!Number.isFinite(id)) return; setError(''); getInspection(id).then(setInspection).catch((reason: Error) => setError(reason.message)); }, [id]);
  useEffect(load, [load]);
  if (error) return <ErrorState message={error} onRetry={load} />;
  if (!inspection) return <LoadingState message="Loading saved evidence, findings, and audit history…" />;
  const failed = inspection.findings.filter((finding) => finding.status === 'FAIL').length; const uncertain = inspection.findings.filter((finding) => finding.status === 'UNCERTAIN').length;
  return <div className="animate-enter space-y-6"><div className="page-header"><div><Link href="/history" className="text-xs font-bold text-teal-800">← Inspection history</Link><h1 className="page-title mt-2">Inspection #{inspection.id}</h1><p className="page-copy">{inspection.original_filename} · {formatDate(inspection.created_at)}</p></div><div className="flex flex-wrap gap-2"><a className="button-secondary" href={reportUrl(inspection.id)} target="_blank" rel="noreferrer"><Download size={16} />PDF report</a><button className="button-secondary" onClick={load}><RefreshCw size={16} />Refresh</button></div></div>

    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6"><Card label="Automated result"><StatusBadge status={inspection.overall_status} /></Card><Card label="Findings"><strong className="text-lg text-rose-700">{failed} failed</strong><span className="text-xs text-slate-500"> · {uncertain} uncertain</span></Card><Card label="Review status"><strong className="text-sm text-navy">{REVIEW_LABELS[inspection.review?.review_status ?? 'NOT_REVIEWED']}</strong></Card><Card label="Image"><strong className="capitalize text-navy">{inspection.quality.status ?? 'unknown'}</strong><span className="text-xs text-slate-500"> · original geometry</span></Card><Card label="Gemini extraction"><strong className="text-sm uppercase text-navy">{inspection.gemini_status?.status ?? 'not recorded'}</strong><span className="text-xs text-slate-500"> · {inspection.gemini_status?.image_readability ?? 'not assessed'}</span></Card><Card label="Reader → rules"><strong className="text-sm uppercase text-navy">{inspection.ocr_engine}</strong><span className="text-xs text-slate-500"> · {inspection.rule_engine_version}</span></Card></section>

    {inspection.original_overall_status && inspection.original_overall_status !== inspection.overall_status && <div className="notice border-blue-200 bg-blue-50 text-blue-950"><History className="mr-2 inline" size={18} />The saved automated result changed after an inspector corrected extracted text: <strong>{STATUS_LABELS[inspection.original_overall_status]}</strong> → <strong>{STATUS_LABELS[inspection.overall_status]}</strong>. Both values remain in the audit record.</div>}
    <WhyThisVerdict inspection={inspection} />
    <section className="grid gap-6 xl:grid-cols-2"><div className="panel p-5"><p className="eyebrow">AI-assisted plain-language explanation</p><p className="mt-3 text-sm leading-6 text-slate-700">{inspection.ai_summary || 'No explanation was stored for this historical inspection.'}</p><p className="mt-3 text-[11px] leading-5 text-slate-500">The deterministic rule engine owns the result. Visual verification and explanations are advisory.</p></div><div className="panel p-5"><p className="eyebrow">Recommended next step</p><ol className="mt-3 space-y-2 text-sm leading-6 text-slate-700">{inspection.recommendation?.map((line, index) => <li key={`${index}-${line}`}><strong className="mr-2 text-teal-800">{index + 1}.</strong>{line}</li>)}</ol></div></section>

    <section className="grid gap-6 2xl:grid-cols-[minmax(0,1.1fr)_minmax(420px,.9fr)]"><div className="panel"><div className="panel-head"><div><h2 className="section-title">Localized evidence</h2><p className="mt-1 text-xs text-slate-500">Select a finding in the matrix to highlight its Gemini-localized region</p></div></div><div className="panel-body"><EvidenceViewer imageUrl={inspectionImageUrl(inspection.id)} findings={inspection.findings} selectedRuleId={selected} onSelect={setSelected} /></div></div><div className="space-y-6"><ImageQuality inspection={inspection} /><ExtractedFields inspection={inspection} onUpdated={setInspection} /></div></section>

    <section className="panel"><div className="panel-head"><div><h2 className="section-title">Declaration coverage</h2><p className="mt-1 text-xs text-slate-500">Backend finding status, validated evidence confidence, version, source citation, and localization availability</p></div></div><DeclarationCoverageMatrix extractedFields={inspection.extracted_fields} findings={inspection.findings} onHighlightRule={(rule) => { setSelected(rule); window.scrollTo({ top: 520, behavior: 'smooth' }); }} /></section>

    <section className="grid gap-6 xl:grid-cols-2"><ReviewForm inspection={inspection} onSaved={load} /><Audit inspection={inspection} /></section>
  </div>;
}

function Card({ label, children }: { label: string; children: React.ReactNode }) { return <div className="panel p-4"><p className="mb-2 text-[10px] font-bold uppercase tracking-[.12em] text-slate-400">{label}</p><div>{children}</div></div>; }

function ImageQuality({ inspection }: { inspection: Inspection }) {
  const quality = inspection.quality; const metrics = [['Blur score', quality.blur_score], ['Glare ratio', quality.glare_ratio], ['Local contrast', quality.local_contrast], ['Dimensions', quality.width && quality.height ? `${quality.width} × ${quality.height}` : undefined], ['Format', quality.format], ['Size', formatBytes(inspection.file_size_bytes)]];
  const warnings = quality.warnings ?? []; const guidance = quality.guidance_notes ?? [];
  return <div className="panel"><div className="panel-head"><h2 className="section-title">Image quality</h2><span className={`rounded-full px-2 py-1 text-xs font-bold ${quality.status === 'good' ? 'bg-emerald-50 text-emerald-800' : 'bg-amber-50 text-amber-900'}`}>{String(quality.status ?? 'unknown').toUpperCase()}</span></div><div className="panel-body"><p className="text-sm leading-6 text-slate-700">{warnings.length ? warnings.join(' ') : 'No capture-quality warning was triggered.'}</p>{guidance.length > 0 && <p className="mt-2 text-xs leading-5 text-slate-500">Guidance: {guidance.join(' ')}</p>}<dl className="mt-4 grid grid-cols-2 gap-3">{metrics.map(([label, value]) => <div key={String(label)} className="rounded-xl bg-slate-50 p-3"><dt className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{label}</dt><dd className="mt-1 text-sm font-bold text-navy">{String(value ?? '—')}</dd></div>)}</dl></div></div>;
}

function ExtractedFields({ inspection, onUpdated }: { inspection: Inspection; onUpdated: (inspection: Inspection) => void }) {
  const fields = useMemo(() => Object.entries(inspection.extracted_fields), [inspection]); const [editing, setEditing] = useState(''); const [text, setText] = useState(''); const [reason, setReason] = useState(''); const [actor, setActor] = useState('Inspector'); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function save(field: string) { setBusy(true); setError(''); try { onUpdated(await submitCorrection(inspection.id, field, text, reason, actor)); setEditing(''); setReason(''); } catch (value) { setError(value instanceof Error ? value.message : 'Correction failed.'); } finally { setBusy(false); } }
  return <div className="panel"><div className="panel-head"><div><h2 className="section-title">Extracted fields</h2><p className="mt-1 text-xs text-slate-500">Corrections rerun the same backend rules and are audited</p></div></div><div className="max-h-[560px] divide-y overflow-auto">{fields.map(([name, field]) => { const provenance = inspection.verification?.fields?.[name]; return <div key={name} className="p-4">{editing === name ? <div className="space-y-3"><label><span className="field-label">{fieldLabel(name)}</span><textarea className="field-input min-h-20 py-2" value={text} onChange={(event) => setText(event.target.value)} /></label><label><span className="field-label">Correction reason</span><input className="field-input" value={reason} onChange={(event) => setReason(event.target.value)} required placeholder="Explain what was verified on the label" /></label><label><span className="field-label">Actor</span><input className="field-input" value={actor} onChange={(event) => setActor(event.target.value)} /></label>{error && <p className="text-xs text-rose-700">{error}</p>}<div className="flex gap-2"><button className="button-primary !min-h-9" disabled={!text.trim() || !reason.trim() || busy} onClick={() => save(name)}><Save size={14} />{busy ? 'Saving…' : 'Save & re-evaluate'}</button><button className="button-secondary !min-h-9" onClick={() => setEditing('')}>Cancel</button></div></div> : <div className="flex items-start gap-3"><div className="min-w-0 flex-1"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{fieldLabel(name)}</p><p className={`mt-1 break-words text-sm ${field.text ? 'font-semibold text-navy' : 'italic text-slate-400'}`}>{field.text || 'Not detected'}</p><p className="mt-1 text-[11px] text-slate-500">{confidence(field.confidence)} · {field.source === 'human_correction' ? 'human correction' : verificationLabel(provenance?.verification_source)}</p>{provenance?.review_required && <p className="mt-1 text-[11px] font-bold text-amber-800">Manual review required{provenance.ocr_value && provenance.gemini_value ? ` · OCR: ${provenance.ocr_value} · AI: ${provenance.gemini_value}` : ''}</p>}</div><button className="focus-ring rounded-lg p-2 text-slate-500 hover:bg-slate-100 hover:text-teal-800" onClick={() => { setEditing(name); setText(field.text); setError(''); }} aria-label={`Correct ${fieldLabel(name)}`}><Edit3 size={16} /></button></div>}</div>; })}</div></div>;
}

function verificationLabel(source?: string | null): string { const labels: Record<string, string> = { GEMINI_DETERMINISTICALLY_VALIDATED: 'Gemini read · deterministic validation passed', CONFLICT: 'conflicting Gemini candidates', MISSING: 'not detected', UNREADABLE: 'unreadable', MANUALLY_CORRECTED: 'manual correction' }; return source ? (labels[source] ?? source.replaceAll('_', ' ').toLowerCase()) : 'evidence not validated'; }

function ReviewForm({ inspection, onSaved }: { inspection: Inspection; onSaved: () => void }) {
  const [status, setStatus] = useState<ReviewStatus>(inspection.review?.review_status ?? 'NOT_REVIEWED'); const [actor, setActor] = useState(inspection.review?.reviewed_by ?? 'Inspector'); const [notes, setNotes] = useState(inspection.review?.review_notes ?? ''); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  async function save(event: FormEvent) { event.preventDefault(); setBusy(true); setMessage(''); try { await submitReview(inspection.id, status, actor, notes); setMessage('Review decision saved to the audit trail.'); onSaved(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Review save failed.'); } finally { setBusy(false); } }
  return <form onSubmit={save} className="panel"><div className="panel-head"><div><h2 className="section-title">Inspector decision</h2><p className="mt-1 text-xs text-slate-500">Independent from the automated result</p></div><ShieldCheck className="text-teal-700" /></div><div className="panel-body space-y-4"><label><span className="field-label">Review status</span><select className="field-input" value={status} onChange={(event) => setStatus(event.target.value as ReviewStatus)}>{Object.entries(REVIEW_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label><span className="field-label">Reviewed by</span><input className="field-input" value={actor} onChange={(event) => setActor(event.target.value)} required maxLength={120} /></label><label><span className="field-label">Notes</span><textarea className="field-input min-h-28 py-2" value={notes} onChange={(event) => setNotes(event.target.value)} maxLength={2000} placeholder="Record observations and legal verification performed" /></label>{message && <p className="notice border-slate-200 bg-slate-50 text-slate-700">{message}</p>}<button className="button-primary" disabled={busy || !actor.trim()}><Check size={16} />{busy ? 'Saving…' : 'Save review decision'}</button></div></form>;
}

function Audit({ inspection }: { inspection: Inspection }) {
  const events = inspection.audit_trail ?? []; const corrections = inspection.corrections ?? [];
  return <div className="panel"><div className="panel-head"><div><h2 className="section-title">Audit trail</h2><p className="mt-1 text-xs text-slate-500">Append-only inspection, correction, rule, and review events</p></div><FileText className="text-slate-500" /></div><div className="max-h-[520px] overflow-auto p-5"><ol className="relative border-l border-slate-200 pl-5">{events.map((event) => <li key={event.id} className="relative mb-5 last:mb-0"><span className="absolute -left-[25px] top-1 h-2 w-2 rounded-full bg-teal-700 ring-4 ring-white" /><p className="text-xs font-extrabold text-navy">{event.event_type.replaceAll('_', ' ')}</p><p className="mt-1 text-xs leading-5 text-slate-600">{event.description}</p><p className="mt-1 text-[10px] text-slate-400">{event.actor} · {formatDate(event.created_at)}</p></li>)}</ol>{!events.length && <p className="text-sm text-slate-500">No audit events were returned.</p>}{corrections.length > 0 && <p className="mt-5 border-t pt-4 text-xs font-bold text-slate-600">{corrections.length} field correction{corrections.length === 1 ? '' : 's'} preserved.</p>}</div></div>;
}
