'use client';
import Link from 'next/link';
import { AlertTriangle, Camera, CheckCircle2, FileImage, LoaderCircle, RotateCcw, Upload, X } from 'lucide-react';
import { ChangeEvent, useEffect, useRef, useState } from 'react';
import { StatusBadge } from '@/components/shared/status-badge';
import { getSystemStatus, inspectLabel, inspectionImageUrl } from '@/lib/api-client';
import { confidence, fieldLabel } from '@/lib/format';
import type { Inspection, PackageScope } from '@/lib/types';

export default function NewInspectionPage() {
  const [file, setFile] = useState<File>(); const [preview, setPreview] = useState('');
  const [scope, setScope] = useState<PackageScope>('unknown'); const [category, setCategory] = useState('');
  const [running, setRunning] = useState(false); const [error, setError] = useState(''); const [result, setResult] = useState<Inspection>();
  const [camera, setCamera] = useState(false); const video = useRef<HTMLVideoElement>(null); const stream = useRef<MediaStream | null>(null);
  const [geminiEnabled, setGeminiEnabled] = useState(false);

  useEffect(() => () => { if (preview.startsWith('blob:')) URL.revokeObjectURL(preview); stream.current?.getTracks().forEach((track) => track.stop()); }, [preview]);
  useEffect(() => { getSystemStatus().then((status) => setGeminiEnabled(Boolean(status.gemini?.enabled && status.gemini?.configured))).catch(() => undefined); }, []);
  function choose(next: File) { if (preview.startsWith('blob:')) URL.revokeObjectURL(preview); setFile(next); setPreview(URL.createObjectURL(next)); setResult(undefined); setError(''); }
  function onFile(event: ChangeEvent<HTMLInputElement>) { const selected = event.target.files?.[0]; if (selected) choose(selected); }
  async function openCamera() {
    setError('');
    if (!navigator.mediaDevices?.getUserMedia) { setError('Camera capture is not supported in this browser. Upload an image instead.'); return; }
    try { const media = await navigator.mediaDevices.getUserMedia({ video: { facingMode: { ideal: 'environment' } }, audio: false }); stream.current = media; setCamera(true); setTimeout(() => { if (video.current) video.current.srcObject = media; }, 0); }
    catch { setError('Camera permission was denied or no camera is available. Upload an image instead.'); }
  }
  function closeCamera() { stream.current?.getTracks().forEach((track) => track.stop()); stream.current = null; setCamera(false); }
  function capture() { const current = video.current; if (!current?.videoWidth) return; const canvas = document.createElement('canvas'); canvas.width = current.videoWidth; canvas.height = current.videoHeight; canvas.getContext('2d')?.drawImage(current, 0, 0); canvas.toBlob((blob) => { if (blob) choose(new File([blob], `camera-label-${Date.now()}.jpg`, { type: 'image/jpeg' })); }, 'image/jpeg', .92); closeCamera(); }
  async function run() { if (!file) return; setRunning(true); setError(''); try { setResult(await inspectLabel(file, scope, category)); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Inspection failed.'); } finally { setRunning(false); } }

  return <div className="animate-enter"><div className="page-header"><div><p className="eyebrow">New inspection</p><h1 className="page-title">Capture the declaration panel</h1><p className="page-copy">Use a sharp, straight-on image with the full statutory panel visible. Gemini reads the image once; deterministic backend validators and rules decide what can be trusted.</p></div></div>
    <div className="mb-6 grid grid-cols-3 overflow-hidden rounded-xl border bg-white text-xs font-bold sm:text-sm"><Step n="1" label="Image" active={!running && !result} done={Boolean(result)} /><Step n="2" label="Processing" active={running} done={Boolean(result)} /><Step n="3" label="Result" active={Boolean(result)} done={Boolean(result)} /></div>
    {!result && <div className="grid gap-6 xl:grid-cols-[minmax(0,1.15fr)_minmax(330px,.85fr)]">
      <section className="panel"><div className="panel-head"><h2 className="section-title">1. Label image</h2><span className="text-xs text-slate-500">JPEG, PNG, WebP, BMP, TIFF · max 10 MB</span></div><div className="panel-body">
        {preview ? <div><div className="relative overflow-hidden rounded-xl border bg-slate-100">{/* eslint-disable-next-line @next/next/no-img-element */}<img src={preview} alt="Selected label preview" className="max-h-[520px] w-full object-contain" /><button className="absolute right-3 top-3 grid h-9 w-9 place-items-center rounded-full bg-navy text-white" onClick={() => { setFile(undefined); setPreview(''); }} aria-label="Remove image"><X size={17} /></button></div><div className="mt-3 flex items-center gap-2 text-xs text-slate-600"><FileImage size={16} /><span className="min-w-0 flex-1 truncate">{file?.name}</span><span>{file ? (file.size / 1024 / 1024).toFixed(2) : '0'} MB</span></div></div> : <label className="focus-within:ring-2 focus-within:ring-teal-500 grid min-h-72 cursor-pointer place-items-center rounded-2xl border-2 border-dashed border-slate-300 bg-slate-50 p-8 text-center transition hover:border-teal-600 hover:bg-teal-50/40"><input type="file" accept="image/jpeg,image/png,image/webp,image/bmp,image/tiff" className="sr-only" onChange={onFile} /><span><span className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-white text-teal-800 shadow"><Upload /></span><strong className="mt-4 block text-lg text-navy">Drop or choose a label image</strong><span className="mt-1 block text-sm text-slate-500">Keep every declaration legible and inside the frame</span></span></label>}
        <div className="my-4 flex items-center gap-3 text-xs text-slate-400"><span className="h-px flex-1 bg-slate-200" />OR<span className="h-px flex-1 bg-slate-200" /></div><button className="button-secondary w-full" onClick={openCamera}><Camera size={17} />Use device camera</button>{geminiEnabled && <p className="notice mt-4 border-blue-200 bg-blue-50 text-blue-950">AI-assisted visual verification enabled. Package imagery is processed using the configured Gemini service.</p>}
      </div></section>
      <section className="panel"><div className="panel-head"><h2 className="section-title">2. Package context</h2></div><div className="panel-body space-y-5"><fieldset><legend className="field-label">Market scope</legend><div className="grid gap-2 sm:grid-cols-3 xl:grid-cols-1">{(['unknown', 'domestic', 'imported'] as PackageScope[]).map((value) => <label key={value} className={`cursor-pointer rounded-xl border p-3 text-sm ${scope === value ? 'border-teal-700 bg-teal-50 text-teal-900' : 'border-slate-200'}`}><input className="mr-2 accent-teal-700" type="radio" checked={scope === value} onChange={() => setScope(value)} />{value[0].toUpperCase() + value.slice(1)}</label>)}</div><p className="mt-2 text-xs leading-5 text-slate-500">Country of origin is evaluated only for imported goods. Unknown scope yields an uncertain applicability result when origin is absent.</p></fieldset><label><span className="field-label">Commodity category (optional)</span><input className="field-input" maxLength={120} value={category} onChange={(event) => setCategory(event.target.value)} placeholder="e.g. food, cosmetics, electronics" /><span className="mt-1 block text-xs text-slate-500">Category exceptions are not inferred. Verify special-category obligations manually.</span></label>{error && <p role="alert" className="notice border-rose-200 bg-rose-50 text-rose-900"><AlertTriangle className="mr-2 inline" size={17} />{error}</p>}<button className="button-primary w-full" disabled={!file || running} onClick={run}>{running ? <><LoaderCircle className="animate-spin" size={18} />Inspecting on server…</> : <><CheckCircle2 size={18} />Run deterministic inspection</>}</button><p className="text-center text-[11px] leading-5 text-slate-500">One server request performs image validation, one Gemini visual extraction, deterministic field validation, rule evaluation, evidence generation, and persistence. Exact substage progress is not streamed.</p></div></section>
    </div>}
    {running && <div className="panel mt-6 overflow-hidden"><div className="h-1 animate-pulse bg-mint" /><div className="p-8 text-center"><LoaderCircle className="mx-auto animate-spin text-teal-700" size={34} /><h2 className="mt-4 text-xl font-black text-navy">Server inspection in progress</h2><p className="mx-auto mt-2 max-w-xl text-sm leading-6 text-slate-600">Gemini reads the image once, then deterministic validators and rules produce the result.</p><div className="mx-auto mt-6 grid max-w-3xl gap-2 text-left sm:grid-cols-2">{['Image Quality', 'Gemini Model Routing', 'Single Visual Extraction', 'Deterministic Evidence Validation', 'Deterministic Rule Evaluation', 'Report Preparation'].map((stage) => <div key={stage} className="flex items-center gap-2 rounded-lg border bg-slate-50 px-3 py-2 text-xs font-bold text-slate-700"><span className="h-2 w-2 animate-pulse rounded-full bg-teal-600" />{stage}<span className="ml-auto text-[10px] font-semibold text-slate-400">QUEUED / RUNNING</span></div>)}</div></div></div>}
    {result && <Result result={result} onReset={() => { setResult(undefined); setFile(undefined); setPreview(''); }} />}
    {camera && <div className="fixed inset-0 z-[100] grid place-items-center bg-black/85 p-4" role="dialog" aria-modal="true" aria-label="Camera capture"><div className="w-full max-w-3xl overflow-hidden rounded-2xl bg-navy"><video ref={video} autoPlay playsInline muted className="max-h-[75vh] w-full bg-black object-contain" /><div className="flex justify-center gap-3 p-4"><button className="button-secondary" onClick={closeCamera}><X size={17} />Cancel</button><button className="button-primary" onClick={capture}><Camera size={17} />Capture frame</button></div></div></div>}
  </div>;
}

function Step({ n, label, active, done }: { n: string; label: string; active: boolean; done: boolean }) { return <div className={`flex items-center justify-center gap-2 border-r px-2 py-3 last:border-r-0 ${active ? 'bg-navy text-white' : done ? 'bg-emerald-50 text-emerald-800' : 'text-slate-400'}`}><span className={`grid h-6 w-6 place-items-center rounded-full text-[11px] ${active ? 'bg-mint text-navy' : 'bg-slate-200'}`}>{done ? '✓' : n}</span>{label}</div>; }
function Result({ result, onReset }: { result: Inspection; onReset: () => void }) {
  const shown = Object.entries(result.extracted_fields).filter(([, value]) => value.text);
  return <div className="space-y-6"><section className="panel overflow-hidden"><div className="grid lg:grid-cols-[.8fr_1.2fr]"><div className="bg-navy p-6 text-white"><p className="eyebrow !text-mint">Inspection #{result.id}</p><StatusBadge status={result.overall_status} className="!text-sm" /><p className="mt-4 text-sm leading-6 text-slate-300">This result came from {result.rule_engine_version}; no frontend or generative model computed it.</p><div className="mt-5 flex flex-wrap gap-2"><Link href={`/inspections/${result.id}`} className="button-primary">Open evidence review</Link><button className="button-secondary !border-white/20 !bg-transparent !text-white" onClick={onReset}><RotateCcw size={16} />Another label</button></div></div><div className="p-5"><div className="grid gap-4 sm:grid-cols-4"><Summary label="Image quality" value={result.quality.status ?? 'unknown'} /><Summary label="Image reader" value={result.ocr_engine} /><Summary label="Extraction" value={result.gemini_status?.status ?? 'unavailable'} /><Summary label="Route" value={String(result.gemini_status?.route_reason ?? 'standard image').replaceAll('_', ' ')} /></div><p className="mt-4 text-sm leading-6 text-slate-600">{String(result.quality.details ?? 'Quality analysis completed.')}</p>{result.gemini_status?.enabled && <p className="mt-2 text-xs leading-5 text-slate-500">{result.gemini_status.external_processing_disclosure}</p>}</div></div></section>
    <section className="grid gap-6 xl:grid-cols-2"><div className="panel"><div className="panel-head"><h2 className="section-title">Detected declarations</h2><span className="text-xs text-slate-500">{shown.length} non-empty fields</span></div><div className="divide-y">{shown.slice(0, 8).map(([name, field]) => <div key={name} className="flex gap-3 p-4"><div className="min-w-0 flex-1"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">{fieldLabel(name)}</p><p className="mt-1 break-words text-sm font-semibold text-navy">{field.text}</p><p className="mt-1 text-[11px] font-bold text-teal-800">{verificationLabel(result.verification?.fields?.[name]?.verification_source)}</p></div><span className="font-mono text-xs text-slate-500">{confidence(field.confidence)}</span></div>)}</div></div><div className="panel"><div className="panel-head"><h2 className="section-title">Evidence preview</h2></div><div className="p-4">{/* eslint-disable-next-line @next/next/no-img-element */}<img src={inspectionImageUrl(result.id, true)} alt="Generated evidence preview" className="max-h-[440px] w-full rounded-xl border bg-slate-100 object-contain" /></div></div></section>
    <section className="grid gap-6 xl:grid-cols-2"><div className="panel p-5"><p className="eyebrow">AI-assisted plain-language explanation</p><p className="mt-3 text-sm leading-6 text-slate-700">{result.ai_summary}</p></div><div className="panel p-5"><p className="eyebrow">Recommended next step</p><ol className="mt-3 space-y-2 text-sm leading-6 text-slate-700">{result.recommendation?.map((line, index) => <li key={line}><strong className="mr-2 text-teal-800">{index + 1}.</strong>{line}</li>)}</ol></div></section>
  </div>;
}
function Summary({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-slate-50 p-3"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 truncate text-sm font-extrabold capitalize text-navy">{value}</p></div>; }
function verificationLabel(source?: string | null): string { const labels: Record<string, string> = { GEMINI_DETERMINISTICALLY_VALIDATED: 'Gemini read · deterministic validation passed', CONFLICT: 'Conflicting Gemini candidates', MISSING: 'Not detected', UNREADABLE: 'Unreadable', MANUALLY_CORRECTED: 'Manual correction' }; return source ? (labels[source] ?? source.replaceAll('_', ' ').toLowerCase()) : 'Evidence not validated'; }
